<a href="https://colab.research.google.com/github/Sreelakshmi30/DS-lab/blob/main/Sreelakshmi_Shaji_30_11_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x=np.matrix('1 2 3;4 5 6;7 8 9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
x=np.matrix([[8,7],[3,-5]])
x

matrix([[ 8,  7],
        [ 3, -5]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
x=np.matrix('8 7;3 -5')
b=np.matrix('3;2')
e=np.matmul(x,b)
e

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
identity_matrix=np.identity(5,dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
square_matrix=np.matrix('1 2 3;4 5 6;7 8 9')
identity_matrix=np.identity(3,dtype=int)
mult=np.matmul(square_matrix,identity_matrix)
mult

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
matrix_a=np.matrix('1 3 3;1 4 3;1 3 4')
inverse_a=np.matrix('7 -3 -3;-1 1 0;-1 0 1')
x=np.matmul(matrix_a,inverse_a)
x

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x=np.matrix('8 7;3 -5')
det_x=np.linalg.det(x)
det_x

-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A
a=np.matrix('1 3 3;1 4 3;1 3 4')
det_a=np.linalg.det(a)
det_a

1.0

In [ ]:
# Calculate the inverse of the above matrix A.
a=np.matrix('1 3 3;1 4 3;1 3 4')
inverse_a=np.linalg.inv(a)
inverse_a

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [ ]:
#Create a dictionary to store weatherdata and convert it to a dataframe
import pandas as pd
weatherdata={
"day":['29/11/21','1/12/21','15/11/21','14/8/21','12/11/2021'],
"city":['Kottayam','Ernakulam','Alappuzha','Idukki','Kollam'],
"Temp":['30.45','28.9','34.8','32.7','33'],
"WindSpeed":['60','120','78','70','67']}
weatherdata=pd.DataFrame(weatherdata)

# Display the first five rows of dataframe
weatherdata.head()

#Display the last five rows of dataframe
weatherdata.tail()


day       city   Temp WindSpeed
0    29/11/21   Kottayam  30.45        60
1     1/12/21  Ernakulam   28.9       120
2    15/11/21  Alappuzha   34.8        78
3     14/8/21     Idukki   32.7        70
4  12/11/2021     Kollam     33        67